<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" xmlns:tal="http://xml.zope.org/namespaces/tal">
<head>
  <title>The Pyramid Web Application Development Framework</title>
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
  <meta name="keywords" content="python web application" />
  <meta name="description" content="pyramid web application" />
  <link rel="shortcut icon" href="${request.static_url('sawhoosh:static/favicon.ico')}" />
  <link rel="stylesheet" href="${request.static_url('sawhoosh:static/pylons.css')}" type="text/css" media="screen" charset="utf-8" />
  <link rel="stylesheet" href="http://static.pylonsproject.org/fonts/nobile/stylesheet.css" media="screen">
  <link rel="stylesheet" href="http://static.pylonsproject.org/fonts/neuton/stylesheet.css" media="screen">
  <!--[if lte IE 6]>
  <link rel="stylesheet" href="${request.static_url('sawhoosh:static/ie6.css')}" type="text/css" media="screen" charset="utf-8" />
  <![endif]-->
  
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
  <script type="text/javascript" src="${request.static_url('sawhoosh:static/script.js')}"></script>
</head>
<body>
  <div id="wrap">
    <div id="top">
      <div class="top align-center">
        <div><img src="${request.static_url('sawhoosh:static/pyramid.png')}" width="750" height="169" alt="pyramid"/></div>
      </div>
    </div>
    <div id="middle">
      <div class="middle align-center">
        <p class="app-welcome">
          Welcome to <span class="app-name">sawhoosh</span>, an application generated by<br/>
          the Pyramid web application development framework.
        </p>
      </div>
    </div>
    <div id="bottom">
      <div class="bottom">
        <div id="left" class="align-right">
          ${next.body()}
        </div>
        <div id="right" class="align-left">
          <h2>Navigation</h2>
          <ul class="links">
            <li>
              <a href="/">Home</a>
            </li>
            <li><a href="${request.route_url('search')}">Search</a></li>
            <li><a href="${request.route_url('author')}">Authors</a></li>
            <ul>
                <li><a href="${request.route_url('author_new')}">New</a></li>
            </ul>
            <li><a href="${request.route_url('document')}">Documents</a></li>
            <ul>
                <li><a href="${request.route_url('document_new')}">New</a></li>
            </ul>
            </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="footer">
    <div class="footer">&copy; Copyright 2011, NakedTech, LLC.</div>
  </div>
</body>
</html>
